### ISSUE TITLE
mbed vscode openocd add variables to watch

### ISSUE THREAD

**Issue by pawelm87** [janjongboom/mbed-vscode-generator#1]
Hi,
I used to debug my mbed progtams by openocd but when I add variable to watch all has this same status : "-var-create: unable to create variable object". Some variables has data, by way?

I can step by step the program and watch which functions is run, stop program, put breakepoints - debug is work.
![vscdebug](https://user-images.githubusercontent.com/35663020/59903520-7b898900-9401-11e9-9c28-fc6d5a7cfea5.png)

**Comment by janjongboom** [comment]
@pawelm87 Hard to say. It could be that the loop is unrolled by the compiler and that the variable is optimized away. You could add `-fno-unroll-loops` and see if this makes a difference. Unfortunately this is not something I can influence as part of this project.
