### ISSUE TITLE
python error when debug - UnicodeDecodeError

### ISSUE THREAD

**Issue by pawelm87** [janjongboom/mbed-vscode-generator#2]
Hi,

When I started debug I got this error in console:

> Executing task: mbed.exe compile -m NUCLEO_L152RE --profile=debug <

> [mbed] Working path "C:\Users\...\Desktop\workspace\debug-mbed-os\debug_vscode_gcc_arm_nucleo_l152re\debug-pyocd-js\debug" (program)
> Building project debug (NUCLEO_L152RE, GCC_ARM)
> Scan: debug
> Traceback (most recent call last):
>   File "C:\Users\...\Desktop\workspace\debug-mbed-os\debug_vscode_gcc_arm_nucleo_l152re\debug-pyocd-js\debug\mbed-os\tools\make.py", line 427, in <module>
>     main()
>   File "C:\Users\...\Desktop\workspace\debug-mbed-os\debug_vscode_gcc_arm_nucleo_l152re\debug-pyocd-js\debug\mbed-os\tools\make.py", line 362, in main
>     **default_args_dict(options)
>   File "C:\Users\...\Desktop\workspace\debug-mbed-os\debug_vscode_gcc_arm_nucleo_l152re\debug-pyocd-js\debug\mbed-os\tools\make.py", line 93, in wrapped_build_project
>     print("[ERROR] {}".format(str(e)))
>   File "c:\python27\lib\site-packages\future\types\newstr.py", line 102, in __new__
>     return super(newstr, cls).__new__(cls, value)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xb9 in position 46: ordinal not in range(128)
> [mbed] ERROR: "c:\python27\python.exe" returned error.
>        Code: 1
>        Path: "C:\Users\...\Desktop\workspace\debug-mbed-os\debug_vscode_gcc_arm_nucleo_l152re\debug-pyocd-js\debug"
>        Command: "c:\python27\python.exe -u C:\Users\...\Desktop\workspace\debug-mbed-os\debug_vscode_gcc_arm_nucleo_l152re\debug-pyocd-js\debug\mbed-os\tools\make.py -t GCC_ARM -m NUCLEO_L152RE --profile debug --source . --build .\BUILD\NUCLEO_L152RE\GCC_ARM-DEBUG"
>        Tip: You could retry the last command with "-v" flag for verbose output
> ---
> The terminal process terminated with exit code: 1
> 
> Terminal will be reused by tasks, press any key to close it.

I used js script, target NUCLEO_L152RE, toolchain GCC_ARM, ide VSCODE.

This error occure only when I start debug, I can compile and programing device.
I tryed created new program, import from online compiler, change folder "mbed-os" but I always got this same error.
Someone can help?

**Comment by janjongboom** [comment]
Sorry for the late reply @pawelm87, I didn't realize I was not watching this repository. This sounds a lot like [this issue](https://github.com/ARMmbed/mbed-cli/pull/767) which was a bug in Mbed CLI. Make sure you're using the latest version of Mbed CLI, and if this doesn't solve the problem file a bug in the [Mbed OS](https://github.com/armmbed/mbed-os) repository.

(The build command just invoked Mbed CLI to build, and if that errors out there's nothing this tool can do unfortunately)
