### ISSUE TITLE
✘ Could not find compiler. GCC_ARM_PATH set, but cannot find "C:\Program Files (x86)\GNU Tools ARM Embedded\6 2017-q2-update\bin\arm-none-eabi-gcc"

### ISSUE THREAD

**Issue by raktim-roy** [janjongboom/mbed-vscode-generator#4]
Although the arm-none-eabi-gcc exists in the mentioned path, the tool throws up error? I am on a WIN10 PC (Any slash conversion required?)

Thanks in advance for your help regarding this.

**Comment by raktim-roy** [comment]
I think the cli.js needs to be modified for windows and should look for arm-none-eabi-gcc.exe instead of arm-none-eabi-gcc from mbed-cli settings. Once I fixed that it starts working. Closing this.

**Comment by janjongboom** [comment]
@raktim-roy Good point, if you've already fixed it could you open a pull request?

**Comment by raktim-roy** [comment]
Have created a pull request.
