### ISSUE TITLE
C/C++ standard update

### ISSUE THREAD

**Issue by pilotak** [janjongboom/mbed-vscode-generator#8]
To be compatible with up to date with OS, standards should be updated

https://github.com/ARMmbed/mbed-os/blob/5.15.2/tools/profiles/debug.json
```json
"cStandard": "gnu11",
"cppStandard": "gnu++14",
```

https://github.com/janjongboom/mbed-vscode-generator/blob/8f6dae986854da00e90d98dabf75798d14b4f4b2/cli.js#L248

**Comment by janjongboom** [comment]
Fixed in https://github.com/janjongboom/mbed-vscode-generator/commit/acc601af9109f85f7ab5bdac7cb82f1bf175c79b
